version: 2
updates:
  - package-ecosystem: "yarn" # Your package manager (e.g., "npm", "yarn", "pip")
    directory: "/"           # Location of your package files, typically root ("/")
    schedule:
      interval: "daily"      # Frequency of updates ("daily", "weekly", "monthly")
    open-pull-requests-limit: 10 # Max open PRs by Dependabot
