blank_issues_enabled: false
contact_links:
  - name: Community Discussions
    url: https://discord.gg/NyenAm9T
    about: Have questions, ideas, or feedback? Share them in our Discord community – we're excited to hear from you!
  - name: Documentation
    url: https://github.com/dream-sports-labs/react-native-fast-image#readme
    about: Check out the documentation for usage instructions and API details. 