name: Monitor Open Issues

on:
  workflow_dispatch:
  schedule:
    # This cron expression runs the action at midnight UTC every day
    - cron: '0 0 * * *'

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install axios --legacy-peer-deps

      - name: Run script
        run: node monitor-issues.js
