name: Manual Nightly Release

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Common Setup
        uses: ./.github/actions/setup

      - name: Configure NPM authentication
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm config set @d11:registry https://registry.npmjs.org/

      - name: Check NPM config
        run: npm config list

      - name: Make publish-nightly.sh executable
        run: chmod +x publish-nightly.sh

      - name: Run nightly release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn release:nightly
