name: 'Stale PR/Issue Check'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
permissions:
  pull-requests: write
  issues: write
jobs:
  stale:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/stale@main
        id: stale
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-message: 'This PR is stale because it has been open for more than 14 days with no activity. To mark it as active, either remove the `stale` label or comment. Otherwise it will be closed within 7 days.'
          days-before-stale: 14
          days-before-close: 7
          operations-per-run: 200
          stale-issue-message: "This issue has been marked as stale due to inactivity because it has been open for more than 14 days with no activity. It will be closed if no further activity occurs within 7 days"
          close-pr-message: "This pull request has been closed due to inactivity."
          close-issue-message: "This issue has been closed due to inactivity."

